# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: djangotutorial lint & test & build & deploy & rollback

on:
  push:
    branches: [ "master" ]
    paths: [ "djangotutorial/**" ]

defaults:
  run:
    working-directory: ./djangotutorial

permissions:
  contents: read

jobs:
  djangotutorial-lint-test-build-deploy-rollback:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with ruff
      run: |
        ruff mysite/
        pylint mysite/
    - name: Test with pytest
      run: |
        python mysite/manage.py test
    - name: Test with pytest
      run: |
        python mysite/manage.py test
    - name: Build docker
      run: |
        docker build .
        # docker push ...
    - name: Deploy
      run: |
        echo "Deployed!"
        # some deploy actions
    - name: Rollback
      run: |
        echo "Rollbacked!"
        # some rollback actions

