# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: log_analyzer ruff & pytest

on:
  push:
    branches: [ "master" ]
    paths: [ "log_analyzer/**" ]

defaults:
  run:
    working-directory: ./log_analyzer

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with ruff
      run: |
        ruff src/
    - name: Test with pytest
      run: |
        pytest
